name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Ruby ${{ matrix.ruby }} / ActiveRecord ${{ matrix.active_record }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { active_record: '5.1', ruby: '2.7' }
          - { active_record: '5.2', ruby: '2.7' }
          - { active_record: '6.0', ruby: '2.7' }
          - { active_record: '6.0', ruby: '3.0' }
          - { active_record: '6.0', ruby: '3.1' }
          - { active_record: '6.0', ruby: '3.2' }
          - { active_record: '6.1', ruby: '2.7' }
          - { active_record: '6.1', ruby: '3.0' }
          - { active_record: '6.1', ruby: '3.1' }
          - { active_record: '6.1', ruby: '3.2' }
          - { active_record: '7.0', ruby: '2.7' }
          - { active_record: '7.0', ruby: '3.0' }
          - { active_record: '7.0', ruby: '3.1' }
          - { active_record: '7.0', ruby: '3.2' }
          - { active_record: '7.1', ruby: '2.7' }
          - { active_record: '7.1', ruby: '3.0' }
          - { active_record: '7.1', ruby: '3.1' }
          - { active_record: '7.1', ruby: '3.2' }
          - { active_record: '7.1', ruby: '3.3' }
          - { active_record: '7.2', ruby: '3.1' }
          - { active_record: '7.2', ruby: '3.2' }
          - { active_record: '7.2', ruby: '3.3' }
          - { active_record: '7.2', ruby: '3.4' }
          - { active_record: '8.0', ruby: '3.2' }
          - { active_record: '8.0', ruby: '3.3' }
          - { active_record: '8.0', ruby: '3.4' }
    env:
      ACTIVERECORD: ${{ matrix.active_record }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: |
        bundle exec rake test
